FROM ruby:3.2-slim

ARG http_proxy
ARG https_proxy
ARG no_proxy

ENV http_proxy=${http_proxy}
ENV https_proxy=${https_proxy}
ENV no_proxy=${no_proxy}

RUN apt-get update && apt-get install -y --fix-missing \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile Gemfile.lock yt_media_engine.gemspec ./
COPY lib/yt_media_engine/version.rb ./lib/yt_media_engine/

RUN bundle install

COPY . .

CMD ["ruby", "TGBot.rb"]